task_group_map = {
    "run_host_od_capacity": "capacity_group",
    "run_comp_od_capacity": "capacity_group",
    "run_golden_flights": "pos_od_compartment_group",
    "run_copper_flights": "pos_od_compartment_group",
    "run_zinc_flights": "pos_od_compartment_group",
    "run_market_channels": "market_group",
    "run_market_agents": "market_group",
    "run_market_farebrand": "market_group",
    "run_market_distributors": "market_group",
    "run_market_segments": "market_group",
    "run_pos_od_compartment1": "pos_od_compartment_group",
    "run_pos_od_compartment2": "pos_od_compartment_group",
    'run_pos_od_compartment': 'pos_od_compartment_group',
    "run_market_flights": "pos_od_compartment_group",
    "run_market_significance": "market_group",
    "run_booking_triggers": "triggers_group",
    "run_yield_triggers": "triggers_group",
    "run_pax_triggers": "triggers_group",
    "run_revenue_triggers": "triggers_group",
    "run_events_triggers": "triggers_group",
    "run_opp_trend_triggers": "triggers_group",
    "run_pccp_triggers": "triggers_group",
    "run_etihad_promotions_triggers": "triggers_group",
    "run_emirates_promotions_triggers": "triggers_group",
    "run_group_airline_rating": "ratings_group",
    "run_group_market_rating_Size_of_Market": "ratings_group",
    "run_group_market_rating_Growth_of_market3": "ratings_group",
    "run_group_market_rating_No_of_competitors": "ratings_group",
    "run_group_prod_rating": "ratings_group",
    "run_capacity_rating_blocktime": "ratings_group",
    "run_capacity_rating_freq": "ratings_group",
    "run_capacity_rating_cap": "ratings_group",
    "run_market_rating_mktshare": "ratings_group",
    "run_Restriction_Final": "ratings_group",
    "run_Agility": "ratings_group",
    "run_Agentsf1_Final": "ratings_group",
    "run_compute_competitor_rating": "ratings_group",
    "run_record_4_5": "record_4_5_group",
    "run_record_8_change": "change_file_group",
    "run_record_0_change": "change_file_group",
    "run_record_1_change": "change_file_group",
    "run_record_2_cat_all_change": "change_file_group",
    "run_record_2_cat_25_change": "change_file_group",
    "run_record_2_cat_10_change": "change_file_group",
    "run_record_2_cat_3_fn_change": "change_file_group",
    "run_record_2_cat_11_fn_change": "change_file_group",
    "run_record_2_cat_14_fn_change": "change_file_group",
    "run_record_2_cat_15_fn_change": "change_file_group",
    "run_record_2_cat_23_fn_change": "change_file_group",
    "run_recseg3": "recseg_group",
    "run_recseg2": "recseg_group",
    "run_fares_and_stage_1": "stage_1_fares_group",
    "run_stage_2_rules": "stage_2_rules_group",
    "run_footnote_coll": "available_footnote_group",
    "run_fareladder": "fareladder_group",
    "run_temp_fares_collection": "temp_fares_triggers_group",
    "run_fareId": "fareId_group",
    "run_lff": "lff_hff_group",
    "run_lff_non_sig": "lff_hff_non_sig_group",
    "run_yqyr": "yqyr_process_group",
    "run_yqyr_changetab": "yq_yr_group",
    "run_yqyr_tab178190": "yq_yr_group",
    "run_yqyr_tab171198": "yq_yr_group",
    "run_yqyr_secpos": "yq_yr_group",
    "run_yqyr_zoneflag": "yq_yr_group",
    "run_yqyr_s1change": "yq_yr_group",
    "run_yqyr_s1reverse": "yq_yr_group",
    "send_exec_stats_mail": "mail_group",
    "run_manual_trigger_module_VLYR_pax_1" : "manual_trigger_group",
    "run_manual_trigger_forecast" : "manual_trigger_group",
    "run_manual_trigger_distance" : "manual_trigger_group",
    "run_manual_trigger_capacity" : "manual_trigger_group",
    "run_manual_trigger_target" : "manual_trigger_group",
    "run_landing_page_tile_triggers" : "landing_page_tile_triggers_group",
    "run_manual_trigger_summary_to_landing_page" : "manual_trigger_summary_to_landing_page_group",
    "run_manual_trigger_to_summary" : "manual_trigger_to_summary_group",
    "run_manual_trigger_WMQY_weekly" : "manual_trigger_WMQY_summary_group",
    "run_manual_trigger_WMQY_yearly" : "manual_trigger_WMQY_summary_group",
    "run_manual_trigger_WMQY_rolledUp" : "manual_trigger_WMQY_summary_group",
    "run_manual_trigger_WMQY_event" : "manual_trigger_WMQY_summary_group",
    "run_manual_trigger_WMQY_quarterly" : "manual_trigger_WMQY_summary_group",
    "run_manual_trigger_WMQY_monthly" : "manual_trigger_WMQY_summary_group",
    "run_manual_trigger_WMQY_market_significant" : "manual_trigger_WMQY_summary_group",
}

tasks_in_automation = [
                    "run_manual_trigger_WMQY_monthly",
                    "run_manual_trigger_WMQY_market_significant",
                    "run_manual_trigger_WMQY_quarterly",
                    "run_manual_trigger_WMQY_event",
                    "run_manual_trigger_WMQY_yearly",
                    "run_manual_trigger_WMQY_rolledUp",
                    "run_manual_trigger_WMQY_weekly",
                    "run_landing_page_tile_triggers",
                    "run_manual_trigger_summary_to_landing_page",
                    "run_manual_trigger_to_summary",
                    "run_manual_trigger_WMQY_summary",
                        "run_manual_trigger_module_VLYR_pax_1",
                        "run_manual_trigger_forecast",
                        "run_manual_trigger_distance",
                        "run_manual_trigger_capacity",
                        "run_manual_trigger_target",
                        "run_booking_triggers",
                       "run_pax_triggers",
                       "run_revenue_triggers",
                       "run_yield_triggers",
                       "run_events_triggers",
                       "run_opp_trend_triggers",
                       "run_pccp_triggers",
                       "run_lff",
                       "run_fareId",
                       "run_market_channels",
                       "run_market_farebrand",
                       "run_market_distributors",
                       "run_market_agents",
                       "run_market_segments",
                       "run_golden_flights",
                       "run_copper_flights",
                       "run_zinc_flights",
                       "run_pos_od_compartment",
                       "run_market_flights",
                       "run_host_od_capacity",
                       "run_comp_od_capacity",
                       "run_record_4_5",
                       "run_yqyr_changetab",
                       "run_record_8_change",
                       "run_record_0_change",
                       "run_record_1_change",
                       "run_record_2_cat_all_change.",
                       "run_record_2_cat_25_change",
                       "run_record_2_cat_10_change",
                       "run_record_2_cat_3_fn_change",
                       "run_record_2_cat_11_fn_change",
                       "run_record_2_cat_14_fn_change",
                       "run_record_2_cat_15_fn_change",
                       "run_record_2_cat_23_fn_change",
                       "run_yqyr_tab178190",
                       "run_yqyr_secpos",
                       "run_recseg3",
                       "run_recseg2",
                       "run_yqyr_zoneflag",
                       "run_yqyr_s1change",
                       "run_yqyr_s1reverse",
                       "run_fares_and_stage_1",
                       "run_stage_2_rules",
                       "run_fareladder",
                       "run_temp_fares_collection",
                       "run_footnote_coll",
                       ]